accounts/urls.py
from django.urls import path
from . import views

app_name = "accounts"
urlpatterns = [
    path('register', views.register_user, name="register"),
    path('activate/<uidb64>/<token>', views.activate, name="activate"),
    path('login', views.login_user, name="login"),
    path('logout', views.logout_user, name='logout'),
    path('profile/<int:pk>/', views.AccountPageView.as_view(), name="user_account"),
    path('user/delete/', views.AccountDeleteView.as_view(), name="user_account_delete"),
    path('user/account/<int:pk>/follow_user/', views.AccountUserFollowView.as_view(), name="user_account_follow"),
    path('user/question/<int:pk>/<str:question_text>/follow_user/', views.QuestionUserFollowView.as_view(), name="user_question_follow"),
    path('user/reply/<int:pk>/<str:reply_text>/follow_user/', views.ReplyUserFollowView.as_view(), name="user_reply_follow"),
]

djangodocker/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("", include("polls.urls")),
    path("admin/", admin.site.urls),
    path("accounts/", include("django.contrib.auth.urls")),
    path("accounts/", include("accounts.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

polls/urls.py
from django.urls import path
from . import views
from .views import *

app_name = "polls"
urlpatterns = [
    # /polls/
    path("", QuestionListView.as_view(), name="index"),
    path("<str:username>/bookmarks/", BookmarkListView.as_view(), name="bookmarks"),
    path("<str:username>/<int:pk>/following/", FollowListView.as_view(), name="following"),
    path("about/", AboutView.as_view(), name="about"),
    path("post/", QuestionCreateView.as_view(), name="create_question"),
    path("post/<int:question_id>/<str:question_text>/", QuestionReplyView.as_view(), name="detail"),
    path("post/<int:pk>/<str:question_text>/rate", QuestionRatingView.as_view(), name="question_rating"),
    path("post/<int:pk>/<str:question_text>/bookmark", QuestionBookmarkView.as_view(), name="question_bookmark"),
    path("post/<int:pk>/<str:question_text>/delete/", QuestionDeleteView.as_view(), name="question_delete"),
    path("post/<int:pk>/<str:question_text>/update/", QuestionUpdateView.as_view(), name="question_update"),
    path("reply/<int:question_id>/<str:question_text>/", ReplyCreateView.as_view(), name="create_reply"),
    path("wisqerai/<int:pk>/<str:question_text>/", WisqerBotView.as_view(), name="wisqer_bot"),
    path("reply/<int:pk>/<str:reply_text>/rate", ReplyRatingView.as_view(), name="reply_rating"),
    path("reply/<int:pk>/<str:reply_text>/bookmark", ReplyBookmarkView.as_view(), name="reply_bookmark"),
    path("reply/<int:pk>/<str:reply_text>/delete/", ReplyDeleteView.as_view(), name="reply_delete"),
    path("search/", views.search_view, name='search'),
]

accounts/models.py
from django.db import models
from django.conf import settings
# Create your models here.

class UserFollowing(models.Model):
    user_id = models.ForeignKey(
        settings.AUTH_USER_MODEL, 
        related_name='following', 
        on_delete=models.CASCADE
        )
    
    following_user_id = models.ForeignKey(
        settings.AUTH_USER_MODEL, 
        related_name='followers', 
        on_delete=models.CASCADE
        )
    
    created = models.DateTimeField(auto_now_add=True, db_index=True)

    class Meta:
        constraints = [
            models.UniqueConstraint(fields=['user_id', 'following_user_id'], name='unique_followers')
        ]
        ordering = ['-created']

    def __str__(self):
        return f"{self.user_id} follows {self.following_user_id}"

accounts/forms.py
from typing import Any
from django.forms import EmailField, CharField
from django.utils.translation import gettext_lazy as _
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.core.exceptions import ValidationError
from django import forms

class UserCreationForm(UserCreationForm):
    email = EmailField(
        label=_("Email address"), 
        required=True,
        help_text=_("Required."),
        widget=forms.EmailInput(
            attrs={'class':'form-control',
                   'placeholder':'email@example.com',}
        )
        )
    
    class Meta:
        model = User
        fields = ("username", "email", "password1", "password2")

    def save(self, commit=True):
        user = super(UserCreationForm, self).save(commit=False)
        user.email = self.cleaned_data["email"]
        if commit:
            user.save()
        return user
    
    def __init__(self, *args, **kwargs):
        super(UserCreationForm, self).__init__(*args, **kwargs)
        placeholders = {
            'username': 'Enter username',
            'password1': 'Enter password',
            'password2': 'Re-enter password',
        }
        for field_name, placeholder in placeholders.items():
            self.fields[field_name].widget.attrs.update({
                'class':'form-control',
                'placeholder':placeholder,
            })

class AuthenticationForm(AuthenticationForm):
    def __init__(self, *args, **kwargs):
        super(AuthenticationForm, self).__init__(*args, **kwargs)
        self.fields['username'].widget.attrs.update(
            {'class': 'form-control', 'placeholder': 'Enter username'}
            )
        self.fields['password'].widget.attrs.update(
            {'class': 'form-control', 'placeholder': 'Enter password'}
            )

accounts/views.py
from django.shortcuts import get_object_or_404, render, redirect
from django.http import HttpResponseRedirect, Http404, JsonResponse
from django.urls import reverse, reverse_lazy

from accounts.forms import UserCreationForm
from accounts.forms import AuthenticationForm
from django.contrib.auth import login, logout, get_user_model
from django.contrib.sites.shortcuts import get_current_site
from django.template.loader import render_to_string
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.utils.encoding import force_bytes, force_str
from django.core.mail import EmailMessage, send_mail
from django.contrib import messages
from django.utils import timezone
from djangodocker import settings

from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.views.generic.base import TemplateView
from django.views import View

from polls.models import Question, Reply
from accounts.models import UserFollowing
from . tokens import generate_token
User = get_user_model()


# Create your views here.
def register_user(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            # ensure no email duplicates
            email = form.cleaned_data['email']
            if User.objects.filter(email=email).exists():
                messages.error(request, "An account with this email already exists.")
                return render(request, 'accounts/register.html', {'form': form})
            
            # save user if all checks pass
            user = form.save()
            user.is_active = False
            user.save()
            print(f"User registered. User active? {user.is_active}")

            try:
                # Send the verification link for account activation
                current_site = get_current_site(request)
                subject = "Confirm your email to activate your WISQER account"
                message = render_to_string("accounts/email_confirmation.html", {
                    'username': user.username,
                    'domain': current_site.domain,
                    'uid': urlsafe_base64_encode(force_bytes(user.pk)),
                    'token': generate_token.make_token(user)
                })
                email_confirmation = EmailMessage(
                    subject,
                    message,
                    settings.EMAIL_HOST_USER,
                    [user.email],
                )
                email_confirmation.fail_silently = True
                email_confirmation.send()
                messages.success(request, "Your account has been successfully created. Please check your email to activate your account.")

            except Exception as e:
                messages.error(request, f"An error occurred: {str(e)}")

            return HttpResponseRedirect(reverse('accounts:login'))
    else:
        form = UserCreationForm()

    return render(request, 'accounts/register.html', {'form': form})


def activate(request, uidb64, token):
    print("In activate view")
    try:
        uid = force_str(urlsafe_base64_decode(uidb64))
        user = User.objects.get(pk=uid)
    except (TypeError, ValueError, OverflowError, User.DoesNotExist):
        user = None

    if user is not None and generate_token.check_token(user, token):
        user.is_active = True
        user.save()
        login(request, user)
        return HttpResponseRedirect(reverse('polls:index'))
    else:
        return render(request, 'accounts/activation_failed.html')


def login_user(request):
    get_url = request.GET.get('next', reverse('polls:index'))

    if request.method == 'POST':
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            user = form.get_user()
            print(f"User logged in. User active? {user.is_active}")

            # check if user is active (user confirmed email)
            if not user.is_active:
                messages.error(request, "Please confirm your email to log in.")
                return redirect(reverse('accounts:login'))

            login(request, user)
            submit_url = request.POST.get('next', reverse('polls:index'))
            return HttpResponseRedirect(submit_url)
    else:
        form = AuthenticationForm()

    return render(request, 'accounts/login.html', {'form':form, 'next':get_url})


def logout_user(request):
    logout(request)
    messages.success(request, "Logged out successfully.")
    return redirect(reverse('accounts:login'))


class AccountPageView(TemplateView):
    template_name = "accounts/account_page.html"

    def get_context_data(self, **kwargs):
        user = get_object_or_404(User, pk=kwargs['pk'])

        context = super().get_context_data(**kwargs)
        user_questions = Question.objects.filter(
                pub_date__lte=timezone.now(),
                user=user.id
        ).order_by('-pub_date')
        
        user_replies = Reply.objects.filter(
            pub_date__lte=timezone.now(),
            user=user.id
        ).order_by('-pub_date')
        
        context['account_user'] = user
        context['user_question_list'] = user_questions
        context['user_reply_list'] = user_replies
        context['title'] = f"{user.username}'s Account Page"
        return context


class AccountDeleteView(LoginRequiredMixin, View):
    success_url = reverse_lazy('accounts:login')
    
    def post(self, request):
        deleted_user = User.objects.get(username='[deleted]')
        
        # anonymize user
        user = request.user
        user.question_set.update(user=deleted_user)
        user.reply_set.update(user=deleted_user)

        # delete user
        user.delete()

        # logout user
        logout(request)
        messages.success(request, "Your account has been successfully anonymized and deleted.")

        return HttpResponseRedirect(self.success_url)
    

# FOLLOW VIEWS
def toggle_follow(request, target_user):
    current_user = request.user
    # prevent following yourself
    if current_user == target_user:
        return HttpResponseRedirect(request.META.get('HTTP_REFERER', '/'))
    follow = UserFollowing.objects.filter(user_id=current_user, following_user_id=target_user)
    if follow.exists():
        follow.delete()
        return JsonResponse({"status": f"remove_user_follow", "message": f"removed follow from user"})
    else:
        UserFollowing.objects.create(user_id=current_user, following_user_id=target_user)
        return JsonResponse({"status": f"add_user_follow", "message": f"added follow to user"})


# Follow view for question users
class QuestionUserFollowView(LoginRequiredMixin, View):
    def post(self, request, pk, *args, **kwargs):
        post = get_object_or_404(Question, pk=pk)
        target_user = post.user
        return toggle_follow(request, target_user)

# Follow view for reply users
class ReplyUserFollowView(LoginRequiredMixin, View):
    def post(self, request, pk, *args, **kwargs):
        post = get_object_or_404(Reply, pk=pk)
        target_user = post.user
        return toggle_follow(request, target_user)

# Follow view for account users
class AccountUserFollowView(LoginRequiredMixin, View):
    def post(self, request, pk, *args, **kwargs):
        target_user = get_object_or_404(User, pk=pk)
        return toggle_follow(request, target_user)

accounts/templates/accounts/account_page.html
{% extends "base.html" %}
{% load humanize %}
{% load follow_tags %}
{% load static %}

{% block content %}

<div class="container-fluid mt-7 left-content">
    <div class="row">
        <div class="col-sm">
            <div class="left-menu d-flex flex-column justify-content-between align-items-between">
                <a class="item mt-3" href="{% url 'polls:index' %}"><i class="bi bi-house-fill"></i> Home</a><br>
                
                <a class="item" href="#" data-bs-toggle="tooltip" title="Explore Tab (Coming Soon)"><i class="bi bi-compass-fill"></i> Explore</a><br>
                
                {% if user.is_authenticated %}
                <a class="item" href="{% url 'polls:following' user.username user.id %}"><i class="bi bi-people-fill"></i> Following</a><br>
                {% else %}
                <a class="item" href="{% url 'accounts:login' %}?next={{request.path}}"><i class="bi bi-people-fill"></i> Following</a><br>
                {% endif %}
                
                {% if user.is_authenticated %}
                <a class="item" href="{% url 'polls:bookmarks' user.username %}"><i class="bi bi-bookmark-fill"></i> Bookmarks</a><br>
                {% else %}
                <a class="item" href="{% url 'accounts:login' %}?next={{request.path}}"><i class="bi bi-bookmark-fill"></i> Bookmarks</a><br>
                {% endif %}

                <a class="item" href="{% url 'polls:about' %}"><i class="bi bi-info-circle-fill"></i> About</a><br>
            </div>
        </div>
    </div>  
</div>


<div class="container-fluid mt-7 center-content" style="background-color: hsl(0, 0%, 97%); padding:24px; border-radius:1rem;">
    <div class="row">
        <div class="col-sm">
            {% if account_user.username == '[deleted]' %}
                <h5>This account has been deleted.</h5>
                <hr>
                <p>Profile details are unavailable.</p>

            {% else %}

                {% if user.is_authenticated and user.id == account_user.id %}
                    <h2 class="mx-3"><i class="bi bi-person-circle"></i> Your Account</h2>
                    <div style="display: flex; align-items: center; flex-wrap:wrap;">
                {% else %}
                    <h2 class="mx-3"><i class="bi bi-person-circle"></i> {{account_user.username}}'s Account</h2>
        
                    <div style="display: flex; align-items: center; flex-wrap:wrap;">
                        {% if account_user|is_following_by:user %} <div class="selected-question mx-3 mt-1">Follows you</div> {% endif %}    
                {% endif %}
                        <div class="mx-3 mt-1 follow-button">
                            <a href="{% url 'polls:following' account_user.username account_user.id %}" style="text-decoration:none; color:inherit;">
                                {{account_user.following.all.count}} Following | {{account_user.followers.all.count}} Followers
                            </a>
                        </div>
                        <div>
                            <!-- FOLLOW -->
                            {% if not user.is_authenticated %}
                            <form action="{% url 'accounts:login' %}?next={{request.path}}" style="margin-left: auto;">
                                <button type="submit" class="remove-default-btn follow-button mx-3 mt-1" onclick="event.stopPropagation();">
                                    <i class="bi bi-plus-lg"></i> Follow
                                </button>
                            </form>

                            {% elif account_user.id == user.id %}
                            {% elif account_user.username == '[deleted]' %}
                            
                            {% else %}
                            <form class="interactForm" data-url="{% url 'accounts:user_account_follow' account_user.id %}"
                            data-account-id="{{account_user.id}}" data-csrf-token="{{csrf_token}}" style="margin-left: auto;">
                                
                                {% if user|is_following:account_user %}
                                    <button class="follow-submit-{{account_user.id}} remove-default-btn unfollow-button mx-3 mt-1" type="submit" onclick="event.stopPropagation();">
                                        <i class="follow-{{ account_user.id }} bi bi-person-fill-check"></i> <span class="follow-text-{{ account_user.id }}"></span>
                                    </button>
                                {% else %}
                                    <button class="follow-submit-{{account_user.id}} remove-default-btn follow-button mx-3 mt-1" type="submit" onclick="event.stopPropagation();">
                                        <i class="follow-{{ account_user.id }} bi bi-plus-lg"></i> <span class="follow-text-{{ account_user.id }}">Follow</span>
                                    </button>
                                {% endif %}
            
                            </form>
                            {% endif %}
                        </div>
                    </div>


            <!-- Nav tabs -->
            <ul class="nav nav-tabs mt-3">
                <li class="nav-item">
                <a class="nav-link active" data-bs-toggle="tab" href="#question_list">Questions</a>
                </li>
                <li class="nav-item">
                <a class="nav-link" data-bs-toggle="tab" href="#reply_list">Replies</a>
                </li>
                {% if user.is_authenticated and user.id == account_user.id %}
                <li class="nav-item">
                <a class="nav-link" data-bs-toggle="tab" href="#settings_list">Settings</a>
                </li>
                {% endif %}
            </ul>
            
            <!-- Tab panes -->
            <div class="tab-content">
                <div class="tab-pane container active" id="question_list"><br>
                    {% for question in user_question_list %}
                    <div class="card card-clickable mt-2" data-url="{% url 'polls:detail' question.id question.question_text %}" 
                    onclick="window.location.href=this.dataset.url">
                        <div class="card-body comment">
                            <p class="username-style">
                                <a href="{% url 'accounts:user_account' question.user.id %}">{{question.user.username}}</a> 
                                <span class="date-style">• {{question.pub_date|naturaltime}}</span>
                            </p>
                            <p class="question-body mt-2">{{question.question_text}}</p>
                            {% if question.question_body %}
                                <p class="question-body-2 mt-2"> {{question.question_body|truncatechars:140}}</p>
                            {% endif %}
                            {% if question.question_img %}
                                <div class="image-holder mt-2">
                                    <img src="{{question.question_img.url}}" class="question-image" loading="lazy" />
                                </div>
                            {% endif %}
                        </div>
                    </div>
                    {% empty %}
                        <h6>No questions yet...</h6>
                    {% endfor %}
                </div>
                <div class="tab-pane container fade" id="reply_list"><br>
                    {% for reply in user_reply_list %}
                    <div class="card card-clickable mt-2" data-url="{% url 'polls:detail' reply.question.id reply.question.question_text %}?reply_id={{reply.id}}" 
                    onclick="window.location.href=this.dataset.url">
                        <div class="card-body comment">
                            <p class="username-style">
                                <a href="{% url 'accounts:user_account' reply.user.id %}">{{reply.user.username}}</a> 
                                <span class="date-style">• {{reply.pub_date|naturaltime}}</span>
                            </p>
                            <p class="reply-body mt-2">{{reply.reply_text}}</p>
                        </div>
                    </div>
                    {% empty %}
                        <h6>No replies yet...</h6>
                    {% endfor %}
                </div>
                {% if user.is_authenticated and user.id == account_user.id %}
                <div style="background-color: rgba(245, 245, 245, 0.7); border-radius: 1rem;" class="tab-pane container fade d-flex align-items-end justify-content-center mt-4" id="settings_list"><br>
                    <div class="m-2">
                        <h5 class="mx-2">Delete Account</h5>
                        <hr>
                        <h6 class="mx-2"> Account deletion is permanent. You cannot recover your account after deleting! Your posts and replies will remain and become anonymized.</p>
                        <a data-bs-toggle="modal" data-bs-target="#deleteAccountModal" href="#" style="color: red;">Delete Account</a>
                    </div>
                </div>
                {% endif %}
            </div>
            {% endif %}


            <!-- Delete Account Modal -->
            <div class="modal fade" id="deleteAccountModal" tabindex="-1" aria-labelledby="deleteAccountModal" aria-hidden="true">
                <div class="modal-dialog modal-dialog-centered modal-sm">
                <div class="modal-content">
                    <div class="modal-header d-flex align-items-center justify-content-around">
                        <h5 class="modal-title">Delete Account</h5>
                    </div>
                    <form action="{% url 'accounts:user_account_delete' %}" method="post">
                        {% csrf_token %}
                    
                    <div class="modal-body text-center">
                        <p>Are you sure you want to delete your account?</p>
                        <p>Your account will be deleted. However, your posts and replies will be anonymized.</p>
                        <p style="color: red;">This action cannot be undone.</p>
                    </div>
                    <div class="modal-footer d-flex align-items-center justify-content-around">
                        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancel</button>
                        <button type="submit" class="btn btn-danger">Delete Account</button>
                    </div>
                    </form>
                </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

{% block extra_js %}
<script src="{% static 'polls/app_script.js' %}"></script>
{% endblock %}

accounts/templates/accounts/activation_failed.html
{% autoescape off %}
Activation failed. Please try again.
{% endautoescape %}

accounts/templates/accounts/email_confirmation.html
{% autoescape off %}
Hello {{username}}, welcome to WISQER!

Please confirm your email by clicking the link below to activate your account.

Confirmation Link: https://{{ domain }}{% url 'accounts:activate' uidb64=uid token=token %}

{% endautoescape %}

accounts/templates/accounts/login.html
{% extends "base.html" %}

{% block content %}
<div class="center-content-auth">
    <div class="shadow p-5 mt-7 bg-body" style="border-radius: 1rem;">
    <h1 style="color: darkmagenta;">Login to Wisqer</h1>

    {% if messages %}
        <div class="alert alert-secondary">
            {% for message in messages %}
                {{message}}
            {% endfor %}
        </div>
    {% endif %}

    <form action="{% url 'accounts:login' %}" method="post" novalidate>
        {% csrf_token %}
        {% if form.non_field_errors %}
        <div class="text-danger">
            {% for error in form.non_field_errors %}
            {{ error }}
            {% endfor %}
        </div>
        {% endif %}
        
        {% for field in form %}
        {% if field.errors %}
        <div class="text-danger">
            {{field.errors}}
        </div>
        {% endif %}
        <div class="form-floating mt-3 mb-3">
            {{field}}
            <label for="{{field.id_for_label}}">{{field.label}}</label>
        </div>
        {% endfor %}

        <input type="hidden" name="next" value="{{next}}">
        <button type="submit" class="btn btn-primary mb-5">Login</button>
    </form>

    <h6>Don't have an account? 
        <a href="{% url 'accounts:register' %}">Register here</a>.
    </h6>
    </div>
</div>
{% endblock content %}

accounts/templates/accounts/register.html
{% extends "base.html" %}

{% block content %}
<div class="center-content-auth">
<div class="shadow p-5 mt-7 bg-body" style="border-radius: 1rem;">
<h1 style="color: darkmagenta;">Let's get started.</h1>

{% if messages %}
    {% for message in messages %}
    <div class="text-danger">{{ message }}</div>
    {% endfor %}
{% endif %}

<form action="{% url 'accounts:register' %}" method="post" novalidate>
    {% csrf_token %}
    {% for field in form %}
    {% if field.errors %}
    <div class="text-danger">
        {{field.errors}}
    </div>
    {% endif %}
    <div class="form-floating mt-3 mb-3">
        {{field}}
        <label for="{{field.id_for_label}}">{{field.label}}</label>
    </div>
    {% endfor %}
    <button type="submit" class="btn btn-primary">Register</button>
</form>
</div>
</div>
{% endblock content %}