accounts/urls.py
from django.urls import path
from . import views

app_name = "accounts"
urlpatterns = [
    path('register', views.register_user, name="register"),
    path('activate/<uidb64>/<token>', views.activate, name="activate"),
    path('login', views.login_user, name="login"),
    path('logout', views.logout_user, name='logout'),
    path('profile/<int:pk>/', views.AccountPageView.as_view(), name="user_account"),
    path('user/delete/', views.AccountDeleteView.as_view(), name="user_account_delete"),
    path('user/account/<int:pk>/follow_user/', views.AccountUserFollowView.as_view(), name="user_account_follow"),
    path('user/question/<int:pk>/<str:question_text>/follow_user/', views.QuestionUserFollowView.as_view(), name="user_question_follow"),
    path('user/reply/<int:pk>/<str:reply_text>/follow_user/', views.ReplyUserFollowView.as_view(), name="user_reply_follow"),
]

djangodocker/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("", include("polls.urls")),
    path("admin/", admin.site.urls),
    path("accounts/", include("django.contrib.auth.urls")),
    path("accounts/", include("accounts.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

polls/urls.py
from django.urls import path
from . import views
from .views import *

app_name = "polls"
urlpatterns = [
    # /polls/
    path("", QuestionListView.as_view(), name="index"),
    path("<str:username>/bookmarks/", BookmarkListView.as_view(), name="bookmarks"),
    path("<str:username>/<int:pk>/following/", FollowListView.as_view(), name="following"),
    path("about/", AboutView.as_view(), name="about"),
    path("post/", QuestionCreateView.as_view(), name="create_question"),
    path("post/<int:question_id>/<str:question_text>/", QuestionReplyView.as_view(), name="detail"),
    path("post/<int:pk>/<str:question_text>/rate", QuestionRatingView.as_view(), name="question_rating"),
    path("post/<int:pk>/<str:question_text>/bookmark", QuestionBookmarkView.as_view(), name="question_bookmark"),
    path("post/<int:pk>/<str:question_text>/delete/", QuestionDeleteView.as_view(), name="question_delete"),
    path("post/<int:pk>/<str:question_text>/update/", QuestionUpdateView.as_view(), name="question_update"),
    path("reply/<int:question_id>/<str:question_text>/", ReplyCreateView.as_view(), name="create_reply"),
    path("wisqerai/<int:pk>/<str:question_text>/", WisqerBotView.as_view(), name="wisqer_bot"),
    path("reply/<int:pk>/<str:reply_text>/rate", ReplyRatingView.as_view(), name="reply_rating"),
    path("reply/<int:pk>/<str:reply_text>/bookmark", ReplyBookmarkView.as_view(), name="reply_bookmark"),
    path("reply/<int:pk>/<str:reply_text>/delete/", ReplyDeleteView.as_view(), name="reply_delete"),
    path("search/", views.search_view, name='search'),
]

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% if title %}
        <title>{{ title }}</title>
    {% else %}
        <title>Wisqer</title>
    {% endif %}
    
    {% load bootstrap5 %}
    {% bootstrap_css %}
    {% block extra_css %}{% endblock %}
    {% load static %}
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.3/font/bootstrap-icons.css">
    <link rel="stylesheet" href="{% static 'polls/style.css' %}">

</head>
<body>
    <nav class="navbar navbar-expand-sm navbar-custom fixed-top">
        <div class="container-fluid px-3">
            <button id="w-left-menu-toggler" class="btn navbar-toggler" type="button" style="display: inline;">
                <i class="bi bi-list"></i>
            </button>
            <div class="left-menu w-left-menu-collapse" style="position: absolute; display: none; z-index: 1000;">
                <a class="item" href="{% url 'polls:index' %}"><i class="bi bi-house-fill"></i> Home</a><br><br>
                <a class="item" href="#" data-bs-toggle="tooltip" title="Explore Tab (Coming Soon)"><i class="bi bi-compass-fill"></i> Explore</a><br><br>

                {% if user.is_authenticated %}
                <a class="item" href="{% url 'polls:following' user.username user.id %}"><i class="bi bi-people-fill"></i> Following</a><br><br>
                {% else %}
                <a class="item" href="{% url 'accounts:login' %}?next={{request.path}}"><i class="bi bi-people-fill"></i> Following</a><br><br>
                {% endif %}

                {% if user.is_authenticated %}
                <a class="item" href="{% url 'polls:bookmarks' user.username %}"><i class="bi bi-bookmark-fill"></i> Bookmarks</a><br><br>
                {% else %}
                <a class="item" href="{% url 'accounts:login' %}?next={{request.path}}"><i class="bi bi-bookmark-fill"></i> Bookmarks</a><br><br>
                {% endif %}
                
                <a class="item" href="{% url 'polls:about' %}"><i class="bi bi-info-circle-fill"></i> About</a><br>
            </div>
            <a class="navbar-brand logo flex-shrink-0" href="{% url 'polls:index' %}">WISQER</a>

            <div class="d-flex justify-content-center flex-grow-1">
                <div class="search-box d-flex justify-content-center align-items-center" style="gap: 8px;">
                    <i class="bi bi-search" style="font-size:0.8rem; margin-left: 4px;"></i>
                    <form method="get" id="search-form" class="form-inline">
                        <input id="search-input" type="text" class="form-control" placeholder="search questions..." autocomplete="off"/>
                        <div id="search-results" class="list-group mt-4" style="position: absolute; display: none; z-index: 1000;"></div>
                    </form>
                </div>
            </div>

            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#mynavbar">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="mynavbar">
                <!-- <ul class="navbar-nav me-auto"></ul> -->
                <ul class="navbar-nav ms-auto">
                    {% if user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link navbar-text text-end" href="{% url 'accounts:user_account' request.user.id %}"><i class="bi bi-person-fill"></i> {{ request.user.username }}</a>
                    </li>
                    <li>
                        <a class="nav-link navbar-text text-end" href="{% url 'accounts:logout' %}">Logout</a>
                    </li>
                    {% else %}
                    <li class="nav-item">
                        <a class="nav-link navbar-text text-end" href="{% url 'accounts:register' %}">Register</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link navbar-text text-end" href="{% url 'accounts:login' %}">Login</a>
                    </li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </nav>

    <script>
        function initBasePage() {
            initializeLeftNav();
            search();
        }

        function initializeLeftNav() {
            const leftMenuToggler = document.querySelector('#w-left-menu-toggler');
            const leftMenuCollapse = document.querySelector('.w-left-menu-collapse');
        
            function openLeftMenu() {
                const isHidden = getComputedStyle(leftMenuCollapse).display === 'none';
                leftMenuCollapse.style.display = isHidden ? 'block' : 'none';
            }
        
            leftMenuToggler.addEventListener("click", function(event) {
                event.stopPropagation();
                openLeftMenu();
            });
        }
        function search() {
            const searchInput = document.querySelector('#search-input');
            const searchResults = document.querySelector('#search-results');

            searchInput.addEventListener('input', function() {
                const query = searchInput.value.trim();
                if (query.length < 2) {
                    searchResults.style.display = 'none';
                    return;
                }

                // send ajax request to view
                fetch(`/search/?q=${query}`)
                    .then(response => response.json())
                    .then(data => {
                        // clear previous results
                        while (searchResults.firstChild) {
                            searchResults.removeChild(searchResults.firstChild);
                        }

                        if (data.results.length > 0) {
                            // create result elements
                            data.results.forEach(result => {
                                const item = document.createElement('a');
                                item.href = result.url;
                                item.classList.add('list-group-item', 'list-group-item-action');
                                item.textContent = result.question_text;
                                searchResults.appendChild(item);
                            });
                            searchResults.style.display = 'block'; // show results
                        } else {
                            searchResults.style.display = 'none'; // hide if no results
                        }
                    })
                    .catch(error => {
                        console.error('Error fetching search results:', error);
                        searchResults.style.display = 'none';
                    });
            });

            document.addEventListener('click', function(event) {
                if (!searchResults.contains(event.target) && event.target != searchInput) {
                    searchResults.style.display = 'none';
                }
            });
        }

        document.addEventListener('DOMContentLoaded', initBasePage);
    </script>
    
    <div class="base-page">
        {% block content %}
        {% endblock content %}
    </div>

    {% bootstrap_javascript %}
    {% block extra_js %}{% endblock %}
</body>
</html>